Feature/spell check
AvolitesLtd/TitanManual pull request #113
Opened 2020-09-03 23:12 UTC by garethnunns

Spell checker - run with `npm run spellcheck` from `./website`

Could be added to test?

Resolves #88

2020-09-03 23:45 UTC, garethnunns commented
@Farrser and I made some calls on how things should be spelt based on the most common spelling in the software but feel free to suggest changes or add/remove items from .spelling

2020-09-07 08:53 UTC, Farrser requested changes

2020-09-07 12:33 UTC, garethnunns commented on docs/titan-basics.md
> +display how long you've got before the console shuts down. A warning dialog
Nope, no need https://www.markdownguide.org/basic-syntax/#characters-you-can-escape

2020-09-07 12:34 UTC, garethnunns commented on website/versioned_docs/version-13.0/chases/chase-options.md
> +### Xfade
I'll make this a global change

2020-09-07 12:57 UTC, garethnunns commented on website/versioned_docs/version-13.0/chases/chase-options.md
> +### Xfade
Resolved by ad98f8b

2020-09-07 12:57 UTC, garethnunns commented on docs/networking/connecting-the-arena-to-a-network.md
> +The Arena console has an in-built 1GB TitanNet switch (TNS) that is
Resolved in 3650ecf

2020-09-07 18:59 UTC, Farrser approved these changes

2020-09-07 18:59 UTC, merged