Update using-the-select-buttons-and-wheels.md
AvolitesLtd/TitanManual pull request #126
Opened 2020-09-09 14:10 UTC by icke-siegen

- fixed dashes which were stripped by pandoc
- I prefer noting th . as \<.\> to tmphasize it is a real button (many people don't get this)
- better readability by using a table

2020-09-09 15:52 UTC, garethnunns requested changes

2020-09-09 15:52 UTC, garethnunns commented on docs/controlling-fixtures/using-the-select-buttons-and-wheels.md
> +|button presses         |selection                      |
````suggestion
| Keypresses         | Selection                      |
````
Would be good to capitalise these

2020-09-09 15:52 UTC, garethnunns commented on docs/controlling-fixtures/using-the-select-buttons-and-wheels.md
> +|\<.\>                   |all sub fixtures of selection  |
````suggestion
|\<.\>                   | All sub-fixtures of selection  | 
````
Capitalise & change to sub**-**fixtures

2020-09-09 15:52 UTC, garethnunns commented on docs/controlling-fixtures/using-the-select-buttons-and-wheels.md
> +|n \<.\>                |all sub fixtures of fixture n  |
````suggestion
| **n** \<.\>                |all sub fixtures of fixture **n**  |
````
I think making the letters like this would be clearer

2020-09-09 15:53 UTC, garethnunns commented
This looks much butter, feel we could make it clearer with these suggestions, let me know what you think

2020-09-10 06:41 UTC, icke-siegen commented
Definitely looks much clearer. In the German version it looks like this:

![image](https://user-images.githubusercontent.com/70575174/92690467-5a33f600-f341-11ea-902c-b8b4ce6c5db1.png)

Let me find out the best way to make this happen in the english version (do I need to amend the pull request or what?)

2020-09-10 14:47 UTC, garethnunns commented
This looks great, I'm just going to correct a spelling mistake in an old version of the manual and then merge 👍

2020-09-10 15:10 UTC, garethnunns approved these changes

2020-09-10 15:10 UTC, merged