Correct syntax to delete a cue
AvolitesLtd/TitanManual pull request #253
Opened 2020-10-15 16:16 UTC by icke-siegen

general Titan grammar {command} {item} [target] {confirmation}

2020-10-15 16:32 UTC, Farrser commented on docs/cue-lists/editing-cue-lists.md
> +To delete a cue press \<Delete\>, select the cue in the window, and tab the cue again, or press \<Enter\> or \[Confirm\] to confirm.
tab -> tap

2020-10-15 16:33 UTC, Farrser requested changes
Typo needs fixing

2020-10-16 05:41 UTC, icke-siegen commented on docs/cue-lists/editing-cue-lists.md
> +To delete a cue press \<Delete\>, select the cue in the window, and tab the cue again, or press \<Enter\> or \[Confirm\] to confirm.
yeah... done

2020-10-19 07:54 UTC, Farrser approved these changes

2020-10-19 07:54 UTC, merged