Context Buttons - Context Menu & Window Resize
AvolitesLtd/TitanManual pull request #280
Opened 2020-11-05 01:56 UTC by garethnunns

Resolves #264 

@Farrser all of these may benefit from having the original SVGs rather than the FA icons

@icke-siegen I've taken another punt at some german, let me know how I've done

2020-11-05 07:32 UTC, icke-siegen requested changes
@garethnunns you did quite well as for the language. However I'd suggest:
rubbish bin = Papierkorb
pencil  = Stift
cog = Zahnrad
context menu = Kontextmenü

2020-11-05 10:02 UTC, Farrser commented
Getting this SVGs out of the software is quite a bit of faff, quite happy to stick with these, I think they're all pretty clear

2020-11-05 10:02 UTC, Farrser submitted a review, later dismissed

2020-11-08 12:59 UTC, Farrser approved these changes

2020-11-30 11:52 UTC, merged