Update d7 v17
AvolitesLtd/TitanManual pull request #497
Opened 2024-10-19 10:19 UTC by congoblue

Changes to add D7 into the manual

2024-11-18 11:29 UTC, owaits requested changes

2024-11-18 16:23 UTC, PeterBuddAvo commented on docs/about-the-consoles/fader-wings.md
> +but can also be used with the D9, D7, the Sapphire Touch, the Arena and the
The Tiger Touch Wing will not be supported by the D7.

2024-11-18 16:27 UTC, PeterBuddAvo commented on docs/quick-start/dmx-network-setup.md
> +A console would normally output up to 16 universes itself (32 for D7), further Titan Network Processors (TNP) units would be connected to the network using TitanNet to control up to 64 universes. For
The D9 is also specified as running 32 universes without additional processors.

2024-11-18 16:28 UTC, PeterBuddAvo commented on docs/system-settings/dmx-output-mapping.md
> +The console itself will generate DMX output for up to 16 universes (32 for D7), above that you can network the console to one
D7 and D9 both support 32 universes out of the box.

2024-11-18 16:29 UTC, PeterBuddAvo commented on docs/system-settings/external-displays.md
> +provided on the console (HDMI on Diamond 9 and Diamond 7, DVI on other consoles, except Pearl Expert and Tiger Touch 1
The ports on the back of a D7 are display port.

2024-11-18 16:30 UTC, PeterBuddAvo commented on docs/titan-basics/other-parts-of-the-touch-screen.md
> +On Diamond 9 / Diamond 7 the toolbar is replaced by a small <Keys.ContextKey>Tools</Keys.ContextKey> button at the top
On the D7 it is on the top left of the left hand screen on a 2 screen or middle screen on a 3 screen.

2024-11-18 16:32 UTC, PeterBuddAvo commented on docs/titan-basics/workspace-windows.md
> +of the A-G menu buttons and above the wheel displays (except on Diamond 9, Diamond 7,  Sapphire Touch and Titan Go where
for A-G buttons do you mean the softkey buttons? I think these are generally referred to as soft key buttons elsewhere.

2024-11-18 16:36 UTC, PeterBuddAvo commented on docs/titan-reference/button-reference.md
> + Used to start and end pattern selection (such as odd/even) within a range of selected fixtures. See [Selecting fixtures using a pattern](../controlling-fixtures.md#selecting-fixtures-using-a-pattern
Also Pattern/All on the T3.

2024-11-26 16:23 UTC, PeterBuddAvo reviewed
Sorry bunch of changes that I didn't spot last time I went through this. Hopefully these are the last ones.

2024-11-26 16:23 UTC, PeterBuddAvo commented on docs/titan-basics/workspace-windows.md
> +On Diamond 9 and Diamond 7 the context menu buttons are in the top left hand corner of the right
The context menu on the D7 is not in the same place as on the D9. It is just in each individual window more similar to the sapphire.

2024-11-26 16:23 UTC, PeterBuddAvo commented on docs/titan-basics/workspace-windows.md
> +On the Diamond 9 and Diamond 7, the halo colour set on playbacks is used in the level bargraph lighting and the playback indicator.
I think bar graph is normally 2 words?

As previously mentioned that isn't what is on the D7 but this sentence could be interpreted either way.

2024-12-10 13:07 UTC, merged